<a href="https://colab.research.google.com/github/HydrOpOtesJA99/A.I-learning/blob/main/15_%ED%95%99%EC%8A%B5%EC%9D%B4_%EC%9E%98_%EB%90%98%EB%8A%94_%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 15_학습이_잘되는_모델

1. 사용할 레이어
  *   tf.keras.layers.BtachNormalization()
  *   tf.keras.layers.Activation('swish')
2. 데이터
  *   보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  *   아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [3]:
# 라이브러리 사용

import pandas as pd
import tensorflow as tf

## 1. 보스턴 집값 예측 (13차시 코드 그대로 가지고 옴)

### 1) 과거의 데이터 준비 (변경점 X)

In [8]:
# 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 보스턴.head() # 파일경로 제대로 연결되었는지 확인
print(보스턴.columns)

# 종속변수, 독립변수 준비
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 
              'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

print('독립변수(행,열):',독립.shape, ', 종속변수(행,열):',종속.shape)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
독립변수(행,열): (506, 13) , 종속변수(행,열): (506, 1)


### **2) 모델의 구조를 만든다 (본 차시에서 가장 봐야할 곳)**

#### 기존코드)

In [7]:
# 모델의 구조를 만든다 (기존 코드)

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation ='swish')(X)
H = tf.keras.layers.Dense(8, activation ='swish')(H)
H = tf.keras.layers.Dense(8, activation ='swish')(H)
Y = tf.keras.layers.Dense(1)(H) # 'H'로 바꾸는것 잊지말기
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

#### 변경코드)

In [9]:
# 모델의 구조를 만든다

X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H) # 'H'로 바꾸는것 잊지말기
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')



*   Batchnormalization을 Dense, Activation 사이에 위치시키면 더욱 효율적이기에 Dense, Activation을 분리하였다


### 2-1) 만든 모델의 확인

In [10]:
# 만든 모델의 확인
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_12 (Dense)            (None, 8)                 112       
                                                                 
 batch_normalization_3 (Batc  (None, 8)                32        
 hNormalization)                                                 
                                                                 
 activation_3 (Activation)   (None, 8)                 0         
                                                                 
 dense_13 (Dense)            (None, 8)                 72        
                                                                 
 batch_normalization_4 (Batc  (None, 8)                32        
 hNormalization)                                           

### 3) 모델을 학습시킨다.

In [14]:
# 모델을 학습시킨다
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 3ms/step - loss: 13.0329
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 9.6716
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 9.7377
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 11.7777
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 9.4721
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 9.8850
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 8.8223
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 9.9854
Epoch 9/10
16/16 [==============================] - 0s 3ms/step - loss: 8.1960
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 10.9586




*   **BatchNormalization을 사용하면 loss 값이 더 작아짐을 확인하였다.**


### 4) 모델을 이용한다

In [13]:
# 모델을 이용한다

print(model.predict(독립[:5]))
print(종속[:5])

[[29.447016]
 [26.24085 ]
 [34.8152  ]
 [34.31772 ]
 [34.647038]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 2. 아이리스 품종 분류 (13차시 코드 그대로)

### 1) 과거의 데이터 준비

In [19]:
# 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

### 1-1) 원핫인코딩(범주형 데이터)

In [20]:
# 원핫인코딩

아이리스 = pd.get_dummies(아이리스)
아이리스.head
#print(아이리스.columns)

<bound method NDFrame.head of      꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]>

In [21]:
# 종속변수, 독립변수 설정

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


### **2) 모델의 구조를 만든다 (본 차시에서 가장 봐야할 곳)**

#### 기존코드)

In [22]:
# 모델의 구조를 만든다

X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

#### 변경코드)

In [23]:
# 모델의 구조를 만든다

X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H) 
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

### 2-1) 만든 모델의 확인

In [24]:
# 만든 모델의 확인

model.summary()

Model: "model_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_28 (Dense)            (None, 8)                 40        
                                                                 
 batch_normalization_9 (Batc  (None, 8)                32        
 hNormalization)                                                 
                                                                 
 activation_9 (Activation)   (None, 8)                 0         
                                                                 
 dense_29 (Dense)            (None, 8)                 72        
                                                                 
 batch_normalization_10 (Bat  (None, 8)                32        
 chNormalization)                                          

### 3) 모델을 학습시킨다.

In [26]:
# 모델을 학습시킨다

model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0318 - accuracy: 0.9933
Epoch 2/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1210 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0255 - accuracy: 0.9933
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0306 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0852 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0181 - accuracy: 0.9933
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0569 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0510 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0304 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0272 - accuracy: 0.9867




*   **BatchNormalization을 사용하면 accuracy 값이 더 높아짐을 확인하였다.**


### 4) 모델을 이용한다

In [28]:
print(model.predict(독립[0:5]))
print(종속[0:5])

[[1.0000000e+00 1.0812682e-11 3.0433026e-12]
 [1.0000000e+00 3.5738221e-08 5.1481736e-10]
 [1.0000000e+00 7.4403977e-10 1.2168346e-11]
 [9.9999976e-01 1.9793281e-07 1.3180576e-11]
 [1.0000000e+00 5.8454118e-12 6.2150041e-13]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
