<a href="https://colab.research.google.com/github/HydrOpOtesJA99/A.I-learning/blob/main/16_%EC%B5%9C%EC%A2%85_CODE_13%EC%B0%A8_%EC%9D%B4%ED%9B%84_%EB%82%B4%EC%9A%A9_%EC%B6%94%EA%B0%80_%ED%95%84%EC%9A%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 16_최종_CODE

1. 사용할 레이어
  *   tf.keras.layers.BtachNormalization()
  *   tf.keras.layers.Activation('swish')
2. 데이터
  *   보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  *   아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용

import pandas as pd
import tensorflow as tf

## 1. 보스턴 집값 예측 (실수형 데이터)

### 1) 과거의 데이터 준비

In [3]:
# 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 파일경로 제대로 연결되었는지 확인
## 보스턴.head() 

print(보스턴.columns) # 필드명이 출력됨

# 종속변수, 독립변수 준비

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 
              'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print('독립변수(행,열):',독립.shape, ', 종속변수(행,열):',종속.shape)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
독립변수(행,열): (506, 13) , 종속변수(행,열): (506, 1)


### 2) 모델의 구조를 만든다 
- 참고(https://www.tensorflow.org/guide/keras?hl=ko)

In [4]:
# 모델의 구조를 만든다 
## tf.keras는 딥러닝 모델을빌드하고 학습시키기 위한 Tensorflow의 상위 수준 API
### 히든레이어 활성화 함수 관련 설명 git hub / A.I-learning 12_히든레이어.ipynb 확인
### URL: https://url.kr/bowe6l 

X = tf.keras.layers.Input(shape=[13]) # '13' -> 준비된 '독립변수'의 개수 

H = tf.keras.layers.Dense(8)(X)  # '8' -> 준비된 '종속변수'의 개수
H = tf.keras.layers.BatchNormalization()(H) 
H = tf.keras.layers.Activation('swish')(H) 

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)  # 'H'로 바꾸는것 잊지말기!!
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')  # MSE(Mean Squeared Error) - 오차의 제곱에 대한 평균, 값과 정확도는 반비례

### 2-1) 만든 모델의 확인

In [5]:
# 만든 모델의 확인

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 8)                 112       
                                                                 
 batch_normalization (BatchN  (None, 8)                32        
 ormalization)                                                   
                                                                 
 activation (Activation)     (None, 8)                 0         
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 batch_normalization_1 (Batc  (None, 8)                32        
 hNormalization)                                             

### 3) 모델을 학습시킨다.

In [6]:
# 모델을 학습시킨다
# fit -> 학습하는 도구

model.fit(독립, 종속, epochs=1000, verbose=0)  # verbose=0 -> 학습현황이 뜨지 않게 함
model.fit(독립, 종속, epochs=10)  # epochs=N -> N번 학습 명령어

# 학습이 끝나면 <keras.callbacks.History at 0x7fa7743df890> 이런 word 뜸

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 10.0964
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 12.9559
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 12.3318
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 12.3908
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 12.4621
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 11.9606
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 11.6852
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 11.7953
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 10.8449
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 9.6254


### 3-1) 학습한 가중치 확인

In [ ]:
# 학습한 가중치 확인
## 가중치 해석은 github A.I-learning / 11_아이리스_품종_분류_실습.ipynb 확인 (제일 밑에 적혀 있음)
### URL: https://url.kr/4i6ap9

model.get_weights()

### 4) 모델을 이용한다

In [8]:
# 모델을 이용한다
# 학습 완료 모델에 새로운 값을 넣어 결과 확인

print(model.predict(독립[:5])) # '독립[:5]' -> [파이썬의 slicing] 맨 앞에서부터 predict한 값을 5개 print하라
print(종속[:5])

# 독립[-5:] -> 뒤에서부터 5개의 값을 print 하라

[[24.879606]
 [23.896315]
 [32.738857]
 [31.684319]
 [32.737877]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 2. 아이리스 품종 분류 (범주형 데이터)

### 1) 과거의 데이터 준비

In [9]:
# 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head() # 파일경로가 제대로 연결되었는지 확인

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

### 1-1) 원핫인코딩(범주형 데이터)

In [10]:
# 원핫인코딩
## 원핫인 코딩? 범주형 데이터(문자)를 실수형 데이터로 바꾸는 작업

아이리스 = pd.get_dummies(아이리스)
아이리스.head

#print(아이리스.columns)

<bound method NDFrame.head of      꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]>

In [11]:
# 종속변수, 독립변수 설정

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


### 2) 모델의 구조를 만든다 

In [12]:
# 모델의 구조를 만든다 
## tf.keras는 딥러닝 모델을빌드하고 학습시키기 위한 Tensorflow의 상위 수준 API
### 히든레이어 활성화 함수 관련 설명 git hub / A.I-learning 12_히든레이어.ipynb 확인
### URL: https://url.kr/bowe6l 

X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H) 
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation = 'softmax')(H) # softmax -> 비율(0~1사이의 실수)로 예측하기 위해 사용
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy') 

# 분류모델에서는 회귀 모델과 달리loss로 나오는 값이 crossentropy를 통해 계산된 차이값을 이용해 나온다

### 2-1) 만든 모델의 확인

In [13]:
# 만든 모델의 확인

model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_4 (Dense)             (None, 8)                 40        
                                                                 
 batch_normalization_3 (Batc  (None, 8)                32        
 hNormalization)                                                 
                                                                 
 activation_3 (Activation)   (None, 8)                 0         
                                                                 
 dense_5 (Dense)             (None, 8)                 72        
                                                                 
 batch_normalization_4 (Batc  (None, 8)                32        
 hNormalization)                                           

### 3) 모델을 학습시킨다.

In [14]:
# 모델을 학습시킨다

model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

# accuracy = 1 = 모두 맞음, accuracy = 0 = 모두 틀림

Epoch 1/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0482 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0467 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0651 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0593 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0447 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0306 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0354 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0755 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0500 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0341 - accuracy: 0.9867


### 3-1) 학습한 가중치 확인

In [ ]:
# 학습한 가중치 확인
## 가중치 해석은 github A.I-learning / 11_아이리스_품종_분류_실습.ipynb 확인 (제일 밑에 적혀 있음)
### URL: https://url.kr/4i6ap9

model.get_weights()

### 4) 모델을 이용한다

In [16]:
print(model.predict(독립[0:5])) # predict한 값을 처음부터 5개 print 하라
print(종속[0:5])

# 독립[-5:] -> 뒤에서부터 5개의 값을 print 하라

[[9.9999917e-01 8.3063634e-07 3.8844156e-08]
 [9.9999201e-01 7.6074093e-06 3.4506004e-07]
 [9.9999905e-01 9.5004503e-07 3.3506389e-08]
 [9.9999309e-01 6.8411446e-06 1.4255083e-07]
 [9.9999952e-01 4.7728298e-07 1.7136522e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
